/*
* Created by Shrikunj Patel on 1/23/2023.
*/

// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeuHO1_gaZv1XVSqvTzi7r-Jl1MTSbAYI',
    appId: '1:385937273331:android:85daee233c4537b275e286',
    messagingSenderId: '385937273331',
    projectId: 'novel-log-33dd4',
    storageBucket: 'novel-log-33dd4.appspot.com',
    //authDomain: 'flutterfire-e2e-tests.firebaseapp.com',
    //measurementId: 'G-JN95N1JV2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeuHO1_gaZv1XVSqvTzi7r-Jl1MTSbAYI',
    appId: '1:385937273331:android:85daee233c4537b275e286',
    messagingSenderId: '385937273331',
    projectId: 'novel-log-33dd4',
    storageBucket: 'novel-log-33dd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeuHO1_gaZv1XVSqvTzi7r-Jl1MTSbAYI',
    appId: '1:385937273331:android:85daee233c4537b275e286',
    messagingSenderId: '385937273331',
    projectId: 'novel-log-33dd4',
    storageBucket: 'novel-log-33dd4.appspot.com',
    //androidClientId: '406099696497-17qn06u8a0dc717u8ul7s49ampk13lul.apps.googleusercontent.com',
    //iosClientId: '406099696497-irb7edfevfkhi6t5s9kbuq1mt1og95rg.apps.googleusercontent.com',
    //iosBundleId: 'io.flutter.plugins.firebase.messaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeuHO1_gaZv1XVSqvTzi7r-Jl1MTSbAYI',
    appId: '1:385937273331:android:85daee233c4537b275e286',
    messagingSenderId: '385937273331',
    projectId: 'novel-log-33dd4',
    storageBucket: 'novel-log-33dd4.appspot.com',
    //androidClientId: '406099696497-17qn06u8a0dc717u8ul7s49ampk13lul.apps.googleusercontent.com',
    //iosClientId: '406099696497-irb7edfevfkhi6t5s9kbuq1mt1og95rg.apps.googleusercontent.com',
    //iosBundleId: 'io.flutter.plugins.firebase.messaging',
  );
}
